In [7]:
from IPython.core.display import display, HTML
display(HTML("<style>.container { width:95% !important; }</style>"))

# Practica 2 (5%) - Manejo de sentencias

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
''' Este comando intenta cargar plotly. Si ocurre un error es porque 
    posiblemente el módulo no esté instalado. En ese caso,
    el except lo instala automáticamente.
'''
try:
    import plotly.graph_objects as go
except:
    !pip install plotly

$$VSP = v\cdot(a\cdot(1+\varepsilon)+g\cdot \mathbf{grade}+g\cdot C_R)+\frac{1}{2\cdot m}\rho_a \cdot C_D \cdot A\cdot v^3$$

Si se tiene una frecuencia de 10 Hz, quiere decir que los 10 primeros datos se adquirieron en 1 segundo.  lista[0:10] corresponde a los datos del primer segundo.

# Parte I

In [69]:
import os
from tqdm import tqdm

# Definición de variables de entrada
str_path = './data/'
list_name_files = os.listdir(str_path)

float_epsilon = 0.42
float_cr = 6.5e-3
float_cd = 0.75
int_rho_air = 1
int_area = 7
int_mass = 9600 
float_gravity = 9.81

# Ciclo for que recorre uno a uno los archivos xlsx contenidos en la carpeta data
for name_file in tqdm(list_name_files):
    # Lectura del archivo xlsx
    df_file = pd.read_excel(str_path+name_file)
    
    # Extracción de las variables del archivo xlsx
    np_velocity = df_file.velocity.values
    np_aceleration = df_file.aceleration.values
    np_grade = df_file.road_grade.values
    
    # Cálculo de la VSP 
    np_vsp = np_velocity*(np_aceleration*(1+float_epsilon)+float_gravity*np_grade+float_gravity*float_cr)+(int_rho_air*float_cd*int_area*np_velocity**3)/(2*int_mass)
    df_file['vsp'] = np_vsp
    
    #for int_time in range(3,31,3):
        

100%|██████████| 5/5 [00:00<00:00,  7.77it/s]


In [70]:
int_time = 3
int_frequency = 2
int_number_data = int_time*int_frequency # Ventana de datos

np_vsp_avg = np.zeros(np_vsp.shape[0])

for int_ix in tqdm(range(np_vsp.shape[0])):
    
    if int_ix<int_number_data:
        np_vsp_avg[int_ix] = np_vsp[0:int_ix+1].mean()
    else:
        np_vsp_avg[int_ix] = np_vsp[int_ix-int_number_data+1:int_ix+1].mean()

100%|██████████| 1561/1561 [00:00<00:00, 38894.98it/s]


In [43]:
vect_test = np.arange(100)
vect_test

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [63]:
ix = 8
x0 = ix-6+1
xf = ix+1
vect_test[x0:xf],vect_test[x0:xf].mean()

(array([3, 4, 5, 6, 7, 8]), 5.5)

In [53]:
np_vsp_avg[0:8]

array([0., 0., 0., 0., 0., 0., 0., 0.])

# Parte II